mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: blog
  user: root
  password: qwe2476979217
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: "2023-02-12"
  bei_an: 湘ICP备2021010654号-1
  title: 枫枫的个人博客
  qq_image: http://www.baidu.com
  version: 6.0.2
  email: liu2476979217@163.com
  wechat_image: http://www.baidu.com
  name: 枫枫知道
  job: 后端开发
  addr: 湖南长沙111
  slogan: 峰峰博客
  slogan_en: MEILINGBLOG
  web: http://www.mypingfan.top/
  bilibili_url: https://space.bilibili.com
  gitee_url: https://gitee.com/
  github_url: https://github.com/
qq:
  app_id: ""
  key: xx
  redirect: ""
qiniu:
  enable: true
  access_key: "dyFCnM5AqXdQfa2GnS5de5OAeIG2E7m3a90_XO0C"
  secret_key: "kW-7EH4P4tbzdiGbetdOyifr0w2bs5ETB_HQTiFV"
  bucket: "kodomp3"
  cdn: "http://qiniu.mypingfan.top/"
  zone: "z2"
  prefix: "gvb"
  size: 5
email:
  host: ""
  port: 0
  user: ""
  password: ""
  default_from_email: ""
  use_ssl: false
  user_tls: false
jwt:
  secret: ""
  expires: 0
  issuer: ""
